# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
puts "seeding data..."

50.times do 
    User.create(username: Faker::Internet.unique.username, email: Faker::Internet.unique.email, password: Faker::Internet.password, name: Faker::Name.name, birthdate: Faker::Date.birthday(min_age: 16, max_age: 95)) 
end

Product.create(name: "Mediocre Copper Pants", price: 29.05, image_url: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRVtzjYvvuZ2dGItqliDDEKVYki7a1mEatjwJIHQuBhrgKGZYxvMdGtb-rVNaTJUQE0o0MUhxHJNkYaEgt3vkZrnEgdSO-iBwzQved5oLmKOVv6ryeDR8XeOJMs&usqp=CAc", stock_amount: rand(1..100), description: "This is some awesome copper color pants! Mediocre quality, but still a great deal and great value!")
Product.create(name: "Rustic Bronze Chair", price: 16.49, image_url: "http://cdn.shopify.com/s/files/1/0001/8042/0674/products/Halden_Dining_Chair_-_Rustic_Bronze_-_Vintage_Cognac_3_1200x1200.jpg?v=1547227892", stock_amount: rand(1..100), description: "This is a beautiful bronze chair for sale. The color is this georgeous bronze that makes everyone look at it an absolutely fall in love.")
Product.create(name: "Durable Concrete Car", price: 2.45, image_url: "https://design-milk.com/images/2017/08/erik_sommer_fastnet_02.jpg", stock_amount: rand(1..100), description: "Have you ever bought a toy car for your kids? Only to have them break it after only playing with it for a small amount of time. Well, now you will never have to worry about that again. Introducing, the concrete car! Durable concrete construction can withstand any child playing with it as much as they possibily can!")
Product.create(name: "Intelligent Granite Lamp", price: 38.68, image_url: "https://a.1stdibscdn.com/archivesE/upload/1121189/f_252504621631347127338/25250462_datamatics.jpg?width=1500", stock_amount: rand(1..100), description: "What is an intelligent device? This device can turn itself on and off automatically whenever you want it to! It knows your most inner desires and is programmed to know exactly when to turn on and off. It can change colors based on your mood as well. It is constructed of granite, meaning it is beautiful and durable as well!")
Product.create(name: "Rustic Copper Table", price: 20.40, image_url: "http://cdn.shopify.com/s/files/1/0837/2577/products/51Jyw7qaraL_grande.jpeg?v=1454518135", stock_amount: rand(1..100), description: "This is a rustic color copper table! You can put it in the dining room, living room, outside, even in your bedroom! It is beautiful and durable and will fit just about anywhere you could put it. It is circular in shape so you can grab all your friends and play games on it!")
Product.create(name: "Aluminum Pants", price: 61.10, image_url: "https://cdn.shopify.com/s/files/1/0023/3632/5743/products/aluminized-pants-11-oz-opf-carbon-rip-stop-blend-29-to-34-in-trouser-over-pant-333287_500x_crop_center.jpg?v=1618098713", stock_amount: rand(1..100), description: "Ever been out and had your pants rip on you? How embarrassing must that have been? Well, with the purchase of these pants, oh so beautiful pants, it will never happen again! These pants are made of aluminum, so they will never break!")
Product.create(name: "Rustic Rubber Hat", price: 74.32, image_url: "https://www.minnetonkamoccasin.com/media/catalog/product/cache/1922b8ac8aa78ee40ea7791b081b3db1/7/7/775x775-9525-1_4.jpg", stock_amount: rand(1..100), description: "Do you want the ultimate style? Well then you just cannot afford to pass up this all new hat! It is made from 100% rubber, and painted with this beautiful rustic color. It only weighs 2.1 pounds, and will just make you pop out in a crown of people!")
Product.create(name: "Enormous Wooden Keyboard", price: 51.31, image_url: "https://qph.cf2.quoracdn.net/main-qimg-f6851de9c6378ba69e7143872d521573-lq", stock_amount: rand(1..100), description: "This wooden keyboard is no doubt enormous. But, if you have large hands, it will be just perfect for you! At a price of $51.31, it is much more affordable than all of these RGB keyboards flooding the market right now. Do you want the real future of keyboard technology? Then you cannot skip out on this!")
Product.create(name: "Small Concrete Lamp", price: 91.73, image_url: "https://m.media-amazon.com/images/I/71VwK9fFYOS._AC_SS450_.jpg", stock_amount: rand(1..100), description: "You ever find that lamps these days are just to big? Has your kid ever broken one of your expensive lamps? Well now you don't have to worry about that anymore. Durable concrete construction, the size of a pea, the concrete lamp is here!")
Product.create(name: "Fantastic Plastic Hat", price: 8.71, image_url: "https://m.media-amazon.com/images/I/51rR7MRnqBS._AC_SX425_.jpg", stock_amount: rand(1..100), description: "Plastic hat. Very durable. Multiple colors avaliable.")
Product.create(name: "Synergistic Concrete Coat", price: 73.00, image_url: "https://images-dynamic-arcteryx.imgix.net/S22/1350x1710/Arris-Jacket-Concrete.jpg?auto=format%2Ccompress&q=75&ixlib=react-9.0.2&w=926", stock_amount: rand(1..100), description: "Extremely durable coat. Made of concrete so you'll know it will never break or tear on you. Weighs 40 pounds.")
Product.create(name: "Rustic Wooden Table", price: 476.99, image_url: "http://cdn.shopify.com/s/files/1/1496/8454/products/Live_Edge_Mesquite_Slab_Dining_Table_grande.jpg?v=1533608653", stock_amount: rand(1..100), description: "Fantastic table. Big so you can use for a dinning room table. Hand-made as well and quality exceptional.")
Product.create(name: "Intelligent Silk Chair", price: 284.56, image_url: "https://cdn.shopify.com/s/files/1/0332/0384/7212/products/esme-chair-light-weight-linen-ink-cap-product-PDP5_d1e31732-180e-4b41-a607-f3413246c771_980x.jpg?v=1616470646", stock_amount: rand(1..100), description: "Beautiful chair. Knows when to recline for you automatically. Very confortable.")
Product.create(name: "Enormous Silk Table Cloth", price: 13.23, image_url: "https://m.media-amazon.com/images/I/713BtwjQ3SL._AC_SX466_.jpg", stock_amount: rand(1..100), description: "Silk covering for large tables. Good for weddings, events, and home tables as well.")
Product.create(name: "Sleek Steel Clock", price: 61.99, image_url: "https://metallicarts.in/wp-content/uploads/2019/12/Metallic-Arts-Premium-Radial-Black-Stainless-Steel-Wall-Clock-For-Home-Decoration-CL066.jpg", stock_amount: rand(1..100), description: "Clock constructed of steel. Small enough to put on a wall, and with a sleek design, will look very good anywhere you put it")
Product.create(name: "Heavy Duty Rubber Computer", price: 86.89, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0tXYS29kq5jQACPtKcIamrwrZma4v5rsJUQ&usqp=CAU", stock_amount: rand(1..100), description: "Computer made from rubber. So flexibile that it won't even break when you strech it, or throw it at a wall. Absorbs impacts like none other.")
Product.create(name: "Small Wooden Computer", price: 140.17, image_url: "https://content.spiceworksstatic.com/service.community/p/topic_images/0000006996/5720c587/attached_image/_________________________________________________________26.jpg", stock_amount: rand(1..100), description: "Small computer with case constructed from wood. Sleek design and small enough to fit anywhere.")
Product.create(name: "Incredible Paper Pants", price: 30.14, image_url: "https://static.grainger.com/rp/s/is/image/Grainger/26W846_AS01", stock_amount: rand(1..100), description: "Paper pants, just as the title says. Wear them, throw them out, as simple as that. Can also be recycled")
Product.create(name: "Heavy Duty Wooden Hat", price: 65.80, image_url: "https://i.ytimg.com/vi/U7JHFBF_Euw/hqdefault.jpg", stock_amount: rand(1..100), description: "Wooden hat, made from real wood. Stylish as well.")
Product.create(name: "Intelligent Wooden Plate", price: 60.85, image_url: "https://cdn.jewelstreet.com/media/catalog/product/cache/9bf2c66275654ceb40706652c2d22009/m/o/moon_plate_1_1.jpg", stock_amount: rand(1..100), description: "A plate, that knows your desires. It will automatically clean itself after it knows you are done eating. Don't bother doing the dishes anymore, this product will clean itself!")

100.times do 
    Userproduct.create(user_id: rand(1..51), product_id: rand(1..20)) 
end


puts "done seeding"

